### ISSUE TITLE
testthat case #2

### ISSUE THREAD

**Issue by vbaliga** [ropensci/workloopR#2]
Also commented out so that the package can build. I have a hunch for this one - might be how `file.info()` behaves with different OSes/filesystems? Should we nuke this test? 

https://github.com/vbaliga/workloopR/blob/dbd77b7cea594f58c8e8bea0ec5c3128cd6f7686/tests/testthat/test-read-ddf.R#L68

Testthat report:
`test-read-ddf.R:68: failure: get wl metadata pulls return is correct dimensions
names(get_wl_metadata(".")) not equal to c(...).
Lengths differ: 8 is not 11
`

On Windows, here is what I get for column names:
`names(get_wl_metadata(".")
[1] "size"      "isdir"     "mode"      "mtime"     "ctime"     "atime"     "exe"       "exp_names"
`

**Comment by shreeramsenthi** [comment]
Gotcha! From the [`file.info`](https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/file.info) man page, it looks like Win and POSIX/UNIX systems differ in what they will report. So I changed the test from looking for an exact match of  to making sure all the common information is present.

See here: 2a7c190a06dfffd909365aafb22f191c2c33f4b0

**Comment by vbaliga** [comment]
sounds great - thanks!
